/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SelfregRouteImport } from './routes/selfreg'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LetgodRouteImport } from './routes/letgod'
import { Route as JwtDebugRouteImport } from './routes/jwt-debug'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as BecomeRouteImport } from './routes/become'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfregRoute = SelfregRouteImport.update({
  id: '/selfreg',
  path: '/selfreg',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LetgodRoute = LetgodRouteImport.update({
  id: '/letgod',
  path: '/letgod',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtDebugRoute = JwtDebugRouteImport.update({
  id: '/jwt-debug',
  path: '/jwt-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeRoute = BecomeRouteImport.update({
  id: '/become',
  path: '/become',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become': typeof BecomeRoute
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/identity': typeof IdentityRoute
  '/jwt-debug': typeof JwtDebugRoute
  '/letgod': typeof LetgodRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/selfreg': typeof SelfregRoute
  '/success': typeof SuccessRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become': typeof BecomeRoute
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/identity': typeof IdentityRoute
  '/jwt-debug': typeof JwtDebugRoute
  '/letgod': typeof LetgodRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/selfreg': typeof SelfregRoute
  '/success': typeof SuccessRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become': typeof BecomeRoute
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/identity': typeof IdentityRoute
  '/jwt-debug': typeof JwtDebugRoute
  '/letgod': typeof LetgodRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/selfreg': typeof SelfregRoute
  '/success': typeof SuccessRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become'
    | '/callback'
    | '/forgot-password'
    | '/identity'
    | '/jwt-debug'
    | '/letgod'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/selfreg'
    | '/success'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become'
    | '/callback'
    | '/forgot-password'
    | '/identity'
    | '/jwt-debug'
    | '/letgod'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/selfreg'
    | '/success'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/become'
    | '/callback'
    | '/forgot-password'
    | '/identity'
    | '/jwt-debug'
    | '/letgod'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/selfreg'
    | '/success'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeRoute: typeof BecomeRoute
  CallbackRoute: typeof CallbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IdentityRoute: typeof IdentityRoute
  JwtDebugRoute: typeof JwtDebugRoute
  LetgodRoute: typeof LetgodRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SelfregRoute: typeof SelfregRoute
  SuccessRoute: typeof SuccessRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selfreg': {
      id: '/selfreg'
      path: '/selfreg'
      fullPath: '/selfreg'
      preLoaderRoute: typeof SelfregRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letgod': {
      id: '/letgod'
      path: '/letgod'
      fullPath: '/letgod'
      preLoaderRoute: typeof LetgodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt-debug': {
      id: '/jwt-debug'
      path: '/jwt-debug'
      fullPath: '/jwt-debug'
      preLoaderRoute: typeof JwtDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become': {
      id: '/become'
      path: '/become'
      fullPath: '/become'
      preLoaderRoute: typeof BecomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeRoute: BecomeRoute,
  CallbackRoute: CallbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IdentityRoute: IdentityRoute,
  JwtDebugRoute: JwtDebugRoute,
  LetgodRoute: LetgodRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SelfregRoute: SelfregRoute,
  SuccessRoute: SuccessRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
