// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: talk.
// - Entity ID: 102019a1f17fffb72f1a8377d92b04bfca5.
// - Entity Version: 102019a3de49fa17c4ea387da27c6b3f200.
// - Task ID: 69059abed7a8c0e91c950372.
// - Task Root ID: 68fdb6cd7faee3e1b79090cd.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for TalkModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface TalkModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  conference_url: string;
  talk_url: string;
  year: number;
  month: string;
  title: string;
  speaker: string;
  description?: string | null;
  session?: string | null;
  text?: string | null;
}

/**
 * ORM class for Talk entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class TalkORM {
  private static instance: TalkORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a1f17fffb72f1a8377d92b04bfca5';
    this.entityName = 'talk';
    this.entityVersion = '102019a3de49fa17c4ea387da27c6b3f200';
    this.taskId = '69059abed7a8c0e91c950372';
    this.taskRootId = '68fdb6cd7faee3e1b79090cd';
  }

  /**
   * Get singleton instance of TalkORM
   */
  public static getInstance(): TalkORM {
    if (!TalkORM.instance) {
      TalkORM.instance = new TalkORM();
    }
    
    return TalkORM.instance;
  }

  /**
   * Get all Talk records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllTalk(): Promise<TalkModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Talk record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertTalk(data: TalkModel[]): Promise<TalkModel[]> {
    const structured = data.map((item) => CreateData(TalkModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Talk records
   */
  async purgeAllTalk(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Talk records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listTalk(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[TalkModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get talk by Id index
   * This function gets data by index.
   */
  async getTalkById(
    id: string,
  ): Promise<TalkModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) talk by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTalkById(
    id: string,
    data: TalkModel
  ): Promise<TalkModel[]> {
    const index = createIndexId(
      id
    );

    const values = TalkModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete talk by Id index
   */
  async deleteTalkById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get talk by TalkUrl index
   * This function gets data by index.
   */
  async getTalkByTalkUrl(
    talk_url: string,
  ): Promise<TalkModel[]> {
    const index = createIndexTalkUrl(
      talk_url
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) talk by TalkUrl index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTalkByTalkUrl(
    talk_url: string,
    data: TalkModel
  ): Promise<TalkModel[]> {
    const index = createIndexTalkUrl(
      talk_url
    );

    const values = TalkModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete talk by TalkUrl index
   */
  async deleteTalkByTalkUrl(
    talk_url: string
  ): Promise<void> {
    const index = createIndexTalkUrl(
      talk_url
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get talk by MonthYear index
   * This function gets data by index.
   */
  async getTalkByMonthYear(
    month: string,
    year: number,
  ): Promise<TalkModel[]> {
    const index = createIndexMonthYear(
      month,
      year
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) talk by MonthYear index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTalkByMonthYear(
    month: string,
    year: number,
    data: TalkModel
  ): Promise<TalkModel[]> {
    const index = createIndexMonthYear(
      month,
      year
    );

    const values = TalkModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete talk by MonthYear index
   */
  async deleteTalkByMonthYear(
    month: string,
    year: number
  ): Promise<void> {
    const index = createIndexMonthYear(
      month,
      year
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get talk by Speaker index
   * This function gets data by index.
   */
  async getTalkBySpeaker(
    speaker: string,
  ): Promise<TalkModel[]> {
    const index = createIndexSpeaker(
      speaker
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) talk by Speaker index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTalkBySpeaker(
    speaker: string,
    data: TalkModel
  ): Promise<TalkModel[]> {
    const index = createIndexSpeaker(
      speaker
    );

    const values = TalkModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete talk by Speaker index
   */
  async deleteTalkBySpeaker(
    speaker: string
  ): Promise<void> {
    const index = createIndexSpeaker(
      speaker
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get talk by Title index
   * This function gets data by index.
   */
  async getTalkByTitle(
    title: string,
  ): Promise<TalkModel[]> {
    const index = createIndexTitle(
      title
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) talk by Title index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTalkByTitle(
    title: string,
    data: TalkModel
  ): Promise<TalkModel[]> {
    const index = createIndexTitle(
      title
    );

    const values = TalkModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete talk by Title index
   */
  async deleteTalkByTitle(
    title: string
  ): Promise<void> {
    const index = createIndexTitle(
      title
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get talk by DataCreator index
   * This function gets data by index.
   */
  async getTalkByDataCreator(
    data_creator: string,
  ): Promise<TalkModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) talk by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTalkByDataCreator(
    data_creator: string,
    data: TalkModel
  ): Promise<TalkModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = TalkModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete talk by DataCreator index
   */
  async deleteTalkByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get talk by DataUpdater index
   * This function gets data by index.
   */
  async getTalkByDataUpdater(
    data_updater: string,
  ): Promise<TalkModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) talk by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTalkByDataUpdater(
    data_updater: string,
    data: TalkModel
  ): Promise<TalkModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = TalkModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete talk by DataUpdater index
   */
  async deleteTalkByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to TalkModel data array
   */
  private resultToData(values: Data[]): TalkModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return TalkModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as TalkModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized TalkModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is TalkModel => item !== null);
  }
}

/**
 * Convert TalkModel data to Value array
 */
function TalkModelToValues(data: TalkModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'conference_url', type: DataType.string, defaultValue: '' },
    { key: 'talk_url', type: DataType.string, defaultValue: '' },
    { key: 'year', type: DataType.number, defaultValue: 0 },
    { key: 'month', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'speaker', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'session', type: DataType.string, defaultValue: null },
    { key: 'text', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof TalkModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to TalkModel data
 */
function TalkModelFromValues(values: Value[]): TalkModel {
  const data: Partial<TalkModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'conference_url':
        data.conference_url = ParseValue(value, DataType.string) as string;
        break;
      case 'talk_url':
        data.talk_url = ParseValue(value, DataType.string) as string;
        break;
      case 'year':
        data.year = ParseValue(value, DataType.number) as number;
        break;
      case 'month':
        data.month = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'speaker':
        data.speaker = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'session':
        data.session = ParseValue(value, DataType.string) as string | null;
        break;
      case 'text':
        data.text = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as TalkModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for TalkUrl fields
 */
function createIndexTalkUrl(
  talk_url: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, talk_url, 'talk_url'),
  ];

  return {
    fields: ['talk_url'],
    values
  };
}
/**
 * Create index for MonthYear fields
 */
function createIndexMonthYear(
  month: string,
  year: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, month, 'month'),
    CreateValue(DataType.number, year, 'year'),
  ];

  return {
    fields: ['month', 'year'],
    values
  };
}
/**
 * Create index for Speaker fields
 */
function createIndexSpeaker(
  speaker: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, speaker, 'speaker'),
  ];

  return {
    fields: ['speaker'],
    values
  };
}
/**
 * Create index for Title fields
 */
function createIndexTitle(
  title: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, title, 'title'),
  ];

  return {
    fields: ['title'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default TalkORM;