// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: daily_log_entry.
// - Entity ID: 1020199d62a013c7eaca794458834c4f15b.
// - Entity Version: 1020199d679a7e27630be631d86d72e8cf6.
// - Task ID: 68eb211728d943f890989a85.
// - Task Root ID: 68eb0c3d756cd0854078e14b.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";









/**
 * Interface for DailyLogEntryScorecardModel
 */
export interface DailyLogEntryScorecardModel {
  wins: string[];
  needs_improvement: string;
}

/**
 * Interface for DailyLogEntryModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface DailyLogEntryModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  date: string;
  goals: string[];
  execution_notes?: string | null;
  focus_rating: number;
  energy_rating: number;
  difficulties?: string | null;
  performance_score: number;
  win_lose: boolean;
  reasoning?: string | null;
  improvement_notes?: string | null;
  motivation: number;
  anxiety: number;
  confidence: number;
  skills?: string[] | null;
  strengths?: string[] | null;
  scorecard: DailyLogEntryScorecardModel;
}

/**
 * ORM class for DailyLogEntry entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class DailyLogEntryORM {
  private static instance: DailyLogEntryORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '1020199d62a013c7eaca794458834c4f15b';
    this.entityName = 'daily_log_entry';
    this.entityVersion = '1020199d679a7e27630be631d86d72e8cf6';
    this.taskId = '68eb211728d943f890989a85';
    this.taskRootId = '68eb0c3d756cd0854078e14b';
  }

  /**
   * Get singleton instance of DailyLogEntryORM
   */
  public static getInstance(): DailyLogEntryORM {
    if (!DailyLogEntryORM.instance) {
      DailyLogEntryORM.instance = new DailyLogEntryORM();
    }
    
    return DailyLogEntryORM.instance;
  }

  /**
   * Get all DailyLogEntry records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllDailyLogEntry(): Promise<DailyLogEntryModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new DailyLogEntry record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertDailyLogEntry(data: DailyLogEntryModel[]): Promise<DailyLogEntryModel[]> {
    const structured = data.map((item) => CreateData(DailyLogEntryModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all DailyLogEntry records
   */
  async purgeAllDailyLogEntry(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List DailyLogEntry records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listDailyLogEntry(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[DailyLogEntryModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get daily_log_entry by Id index
   * This function gets data by index.
   */
  async getDailyLogEntryById(
    id: string,
  ): Promise<DailyLogEntryModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_log_entry by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyLogEntryById(
    id: string,
    data: DailyLogEntryModel
  ): Promise<DailyLogEntryModel[]> {
    const index = createIndexId(
      id
    );

    const values = DailyLogEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_log_entry by Id index
   */
  async deleteDailyLogEntryById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get daily_log_entry by DataCreator index
   * This function gets data by index.
   */
  async getDailyLogEntryByDataCreator(
    data_creator: string,
  ): Promise<DailyLogEntryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_log_entry by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyLogEntryByDataCreator(
    data_creator: string,
    data: DailyLogEntryModel
  ): Promise<DailyLogEntryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = DailyLogEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_log_entry by DataCreator index
   */
  async deleteDailyLogEntryByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get daily_log_entry by DataUpdater index
   * This function gets data by index.
   */
  async getDailyLogEntryByDataUpdater(
    data_updater: string,
  ): Promise<DailyLogEntryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_log_entry by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyLogEntryByDataUpdater(
    data_updater: string,
    data: DailyLogEntryModel
  ): Promise<DailyLogEntryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = DailyLogEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_log_entry by DataUpdater index
   */
  async deleteDailyLogEntryByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get daily_log_entry by Date index
   * This function gets data by index.
   */
  async getDailyLogEntryByDate(
    date: string,
  ): Promise<DailyLogEntryModel[]> {
    const index = createIndexDate(
      date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_log_entry by Date index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyLogEntryByDate(
    date: string,
    data: DailyLogEntryModel
  ): Promise<DailyLogEntryModel[]> {
    const index = createIndexDate(
      date
    );

    const values = DailyLogEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_log_entry by Date index
   */
  async deleteDailyLogEntryByDate(
    date: string
  ): Promise<void> {
    const index = createIndexDate(
      date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to DailyLogEntryModel data array
   */
  private resultToData(values: Data[]): DailyLogEntryModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return DailyLogEntryModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as DailyLogEntryModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized DailyLogEntryModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is DailyLogEntryModel => item !== null);
  }
}

/**
 * Convert DailyLogEntryModel data to Value array
 */
function DailyLogEntryModelToValues(data: DailyLogEntryModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'date', type: DataType.string, defaultValue: '' },
    { key: 'goals', type: DataType.array, defaultValue: [] },
    { key: 'execution_notes', type: DataType.string, defaultValue: null },
    { key: 'focus_rating', type: DataType.number, defaultValue: 0 },
    { key: 'energy_rating', type: DataType.number, defaultValue: 0 },
    { key: 'difficulties', type: DataType.string, defaultValue: null },
    { key: 'performance_score', type: DataType.number, defaultValue: 0 },
    { key: 'win_lose', type: DataType.boolean, defaultValue: false },
    { key: 'reasoning', type: DataType.string, defaultValue: null },
    { key: 'improvement_notes', type: DataType.string, defaultValue: null },
    { key: 'motivation', type: DataType.number, defaultValue: 0 },
    { key: 'anxiety', type: DataType.number, defaultValue: 0 },
    { key: 'confidence', type: DataType.number, defaultValue: 0 },
    { key: 'skills', type: DataType.array, defaultValue: null },
    { key: 'strengths', type: DataType.array, defaultValue: null },
    { key: 'scorecard', type: DataType.object, defaultValue: {} },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof DailyLogEntryModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to DailyLogEntryModel data
 */
function DailyLogEntryModelFromValues(values: Value[]): DailyLogEntryModel {
  const data: Partial<DailyLogEntryModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'date':
        data.date = ParseValue(value, DataType.string) as string;
        break;
      case 'goals':
        data.goals = ParseValue(value, DataType.array) as string[];
        break;
      case 'execution_notes':
        data.execution_notes = ParseValue(value, DataType.string) as string | null;
        break;
      case 'focus_rating':
        data.focus_rating = ParseValue(value, DataType.number) as number;
        break;
      case 'energy_rating':
        data.energy_rating = ParseValue(value, DataType.number) as number;
        break;
      case 'difficulties':
        data.difficulties = ParseValue(value, DataType.string) as string | null;
        break;
      case 'performance_score':
        data.performance_score = ParseValue(value, DataType.number) as number;
        break;
      case 'win_lose':
        data.win_lose = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'reasoning':
        data.reasoning = ParseValue(value, DataType.string) as string | null;
        break;
      case 'improvement_notes':
        data.improvement_notes = ParseValue(value, DataType.string) as string | null;
        break;
      case 'motivation':
        data.motivation = ParseValue(value, DataType.number) as number;
        break;
      case 'anxiety':
        data.anxiety = ParseValue(value, DataType.number) as number;
        break;
      case 'confidence':
        data.confidence = ParseValue(value, DataType.number) as number;
        break;
      case 'skills':
        data.skills = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'strengths':
        data.strengths = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'scorecard':
        data.scorecard = ParseValue(value, DataType.object) as DailyLogEntryScorecardModel;
        break;
    }
  }
  
  return data as DailyLogEntryModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for Date fields
 */
function createIndexDate(
  date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, date, 'date'),
  ];

  return {
    fields: ['date'],
    values
  };
}

export default DailyLogEntryORM;