// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: politician.
// - Entity ID: 102019a23cf057778efb62fdba9d55ddd06.
// - Entity Version: 102019a27699e0f7060941f7dffce67a884.
// - Task ID: 68ffd975a776938453c6e20b.
// - Task Root ID: 68feec8dcd635a6ece0a6396.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for PoliticianRole
 */
export enum PoliticianRole {
  Unspecified = 0,
  Senator = 1,
  Representative = 2,
}



/**
 * Interface for PoliticianModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface PoliticianModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  name: string;
  party: string;
  state: string;
  role: PoliticianRole;
  years_of_service?: string | null;
  start_year: number;
  end_year?: number | null;
  image_url?: string | null;
  biography?: string | null;
}

/**
 * ORM class for Politician entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class PoliticianORM {
  private static instance: PoliticianORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a23cf057778efb62fdba9d55ddd06';
    this.entityName = 'politician';
    this.entityVersion = '102019a27699e0f7060941f7dffce67a884';
    this.taskId = '68ffd975a776938453c6e20b';
    this.taskRootId = '68feec8dcd635a6ece0a6396';
  }

  /**
   * Get singleton instance of PoliticianORM
   */
  public static getInstance(): PoliticianORM {
    if (!PoliticianORM.instance) {
      PoliticianORM.instance = new PoliticianORM();
    }
    
    return PoliticianORM.instance;
  }

  /**
   * Get all Politician records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllPolitician(): Promise<PoliticianModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Politician record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertPolitician(data: PoliticianModel[]): Promise<PoliticianModel[]> {
    const structured = data.map((item) => CreateData(PoliticianModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Politician records
   */
  async purgeAllPolitician(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Politician records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listPolitician(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[PoliticianModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get politician by Id index
   * This function gets data by index.
   */
  async getPoliticianById(
    id: string,
  ): Promise<PoliticianModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) politician by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPoliticianById(
    id: string,
    data: PoliticianModel
  ): Promise<PoliticianModel[]> {
    const index = createIndexId(
      id
    );

    const values = PoliticianModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete politician by Id index
   */
  async deletePoliticianById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get politician by DataCreator index
   * This function gets data by index.
   */
  async getPoliticianByDataCreator(
    data_creator: string,
  ): Promise<PoliticianModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) politician by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPoliticianByDataCreator(
    data_creator: string,
    data: PoliticianModel
  ): Promise<PoliticianModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = PoliticianModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete politician by DataCreator index
   */
  async deletePoliticianByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get politician by DataUpdater index
   * This function gets data by index.
   */
  async getPoliticianByDataUpdater(
    data_updater: string,
  ): Promise<PoliticianModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) politician by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPoliticianByDataUpdater(
    data_updater: string,
    data: PoliticianModel
  ): Promise<PoliticianModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = PoliticianModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete politician by DataUpdater index
   */
  async deletePoliticianByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get politician by State index
   * This function gets data by index.
   */
  async getPoliticianByState(
    state: string,
  ): Promise<PoliticianModel[]> {
    const index = createIndexState(
      state
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) politician by State index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPoliticianByState(
    state: string,
    data: PoliticianModel
  ): Promise<PoliticianModel[]> {
    const index = createIndexState(
      state
    );

    const values = PoliticianModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete politician by State index
   */
  async deletePoliticianByState(
    state: string
  ): Promise<void> {
    const index = createIndexState(
      state
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get politician by Party index
   * This function gets data by index.
   */
  async getPoliticianByParty(
    party: string,
  ): Promise<PoliticianModel[]> {
    const index = createIndexParty(
      party
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) politician by Party index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPoliticianByParty(
    party: string,
    data: PoliticianModel
  ): Promise<PoliticianModel[]> {
    const index = createIndexParty(
      party
    );

    const values = PoliticianModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete politician by Party index
   */
  async deletePoliticianByParty(
    party: string
  ): Promise<void> {
    const index = createIndexParty(
      party
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get politician by Role index
   * This function gets data by index.
   */
  async getPoliticianByRole(
    role: PoliticianRole,
  ): Promise<PoliticianModel[]> {
    const index = createIndexRole(
      role
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) politician by Role index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPoliticianByRole(
    role: PoliticianRole,
    data: PoliticianModel
  ): Promise<PoliticianModel[]> {
    const index = createIndexRole(
      role
    );

    const values = PoliticianModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete politician by Role index
   */
  async deletePoliticianByRole(
    role: PoliticianRole
  ): Promise<void> {
    const index = createIndexRole(
      role
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to PoliticianModel data array
   */
  private resultToData(values: Data[]): PoliticianModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return PoliticianModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as PoliticianModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized PoliticianModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is PoliticianModel => item !== null);
  }
}

/**
 * Convert PoliticianModel data to Value array
 */
function PoliticianModelToValues(data: PoliticianModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'party', type: DataType.string, defaultValue: '' },
    { key: 'state', type: DataType.string, defaultValue: '' },
    { key: 'role', type: DataType.enumeration, defaultValue: 0 },
    { key: 'years_of_service', type: DataType.string, defaultValue: null },
    { key: 'start_year', type: DataType.number, defaultValue: 0 },
    { key: 'end_year', type: DataType.number, defaultValue: null },
    { key: 'image_url', type: DataType.string, defaultValue: null },
    { key: 'biography', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof PoliticianModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to PoliticianModel data
 */
function PoliticianModelFromValues(values: Value[]): PoliticianModel {
  const data: Partial<PoliticianModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'party':
        data.party = ParseValue(value, DataType.string) as string;
        break;
      case 'state':
        data.state = ParseValue(value, DataType.string) as string;
        break;
      case 'role':
        data.role = ParseValue(value, DataType.enumeration) as PoliticianRole;
        break;
      case 'years_of_service':
        data.years_of_service = ParseValue(value, DataType.string) as string | null;
        break;
      case 'start_year':
        data.start_year = ParseValue(value, DataType.number) as number;
        break;
      case 'end_year':
        data.end_year = ParseValue(value, DataType.number) as number | null;
        break;
      case 'image_url':
        data.image_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'biography':
        data.biography = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as PoliticianModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for State fields
 */
function createIndexState(
  state: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, state, 'state'),
  ];

  return {
    fields: ['state'],
    values
  };
}
/**
 * Create index for Party fields
 */
function createIndexParty(
  party: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, party, 'party'),
  ];

  return {
    fields: ['party'],
    values
  };
}
/**
 * Create index for Role fields
 */
function createIndexRole(
  role: PoliticianRole
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, role, 'role'),
  ];

  return {
    fields: ['role'],
    values
  };
}

export default PoliticianORM;