// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: politician_quote.
// - Entity ID: 102019a23cf057872868fb2ebed61c1984d.
// - Entity Version: 102019a27699e0f7060941f7dffce67a884.
// - Task ID: 68ffd975a776938453c6e20b.
// - Task Root ID: 68feec8dcd635a6ece0a6396.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for PoliticianQuoteIssueCategory
 */
export enum PoliticianQuoteIssueCategory {
  Unspecified = 0,
  Immigration = 1,
  Healthcare = 2,
  ClimateChange = 3,
  NationalDebt = 4,
  WarAuthorization = 5,
  GunControl = 6,
  Infrastructure = 7,
  Abortion = 8,
  SocialSecurity = 9,
  CivilRights = 10,
}



/**
 * Interface for PoliticianQuoteModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface PoliticianQuoteModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  politician_id: string;
  quote_text: string;
  issue_category: PoliticianQuoteIssueCategory;
  source: string;
  date_stated: string;
  context?: string | null;
}

/**
 * ORM class for PoliticianQuote entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class PoliticianQuoteORM {
  private static instance: PoliticianQuoteORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a23cf057872868fb2ebed61c1984d';
    this.entityName = 'politician_quote';
    this.entityVersion = '102019a27699e0f7060941f7dffce67a884';
    this.taskId = '68ffd975a776938453c6e20b';
    this.taskRootId = '68feec8dcd635a6ece0a6396';
  }

  /**
   * Get singleton instance of PoliticianQuoteORM
   */
  public static getInstance(): PoliticianQuoteORM {
    if (!PoliticianQuoteORM.instance) {
      PoliticianQuoteORM.instance = new PoliticianQuoteORM();
    }
    
    return PoliticianQuoteORM.instance;
  }

  /**
   * Get all PoliticianQuote records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllPoliticianQuote(): Promise<PoliticianQuoteModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new PoliticianQuote record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertPoliticianQuote(data: PoliticianQuoteModel[]): Promise<PoliticianQuoteModel[]> {
    const structured = data.map((item) => CreateData(PoliticianQuoteModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all PoliticianQuote records
   */
  async purgeAllPoliticianQuote(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List PoliticianQuote records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listPoliticianQuote(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[PoliticianQuoteModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get politician_quote by Id index
   * This function gets data by index.
   */
  async getPoliticianQuoteById(
    id: string,
  ): Promise<PoliticianQuoteModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) politician_quote by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPoliticianQuoteById(
    id: string,
    data: PoliticianQuoteModel
  ): Promise<PoliticianQuoteModel[]> {
    const index = createIndexId(
      id
    );

    const values = PoliticianQuoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete politician_quote by Id index
   */
  async deletePoliticianQuoteById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get politician_quote by DataCreator index
   * This function gets data by index.
   */
  async getPoliticianQuoteByDataCreator(
    data_creator: string,
  ): Promise<PoliticianQuoteModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) politician_quote by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPoliticianQuoteByDataCreator(
    data_creator: string,
    data: PoliticianQuoteModel
  ): Promise<PoliticianQuoteModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = PoliticianQuoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete politician_quote by DataCreator index
   */
  async deletePoliticianQuoteByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get politician_quote by DataUpdater index
   * This function gets data by index.
   */
  async getPoliticianQuoteByDataUpdater(
    data_updater: string,
  ): Promise<PoliticianQuoteModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) politician_quote by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPoliticianQuoteByDataUpdater(
    data_updater: string,
    data: PoliticianQuoteModel
  ): Promise<PoliticianQuoteModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = PoliticianQuoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete politician_quote by DataUpdater index
   */
  async deletePoliticianQuoteByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get politician_quote by PoliticianId index
   * This function gets data by index.
   */
  async getPoliticianQuoteByPoliticianId(
    politician_id: string,
  ): Promise<PoliticianQuoteModel[]> {
    const index = createIndexPoliticianId(
      politician_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) politician_quote by PoliticianId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPoliticianQuoteByPoliticianId(
    politician_id: string,
    data: PoliticianQuoteModel
  ): Promise<PoliticianQuoteModel[]> {
    const index = createIndexPoliticianId(
      politician_id
    );

    const values = PoliticianQuoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete politician_quote by PoliticianId index
   */
  async deletePoliticianQuoteByPoliticianId(
    politician_id: string
  ): Promise<void> {
    const index = createIndexPoliticianId(
      politician_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get politician_quote by IssueCategoryPoliticianId index
   * This function gets data by index.
   */
  async getPoliticianQuoteByIssueCategoryPoliticianId(
    issue_category: PoliticianQuoteIssueCategory,
    politician_id: string,
  ): Promise<PoliticianQuoteModel[]> {
    const index = createIndexIssueCategoryPoliticianId(
      issue_category,
      politician_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) politician_quote by IssueCategoryPoliticianId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPoliticianQuoteByIssueCategoryPoliticianId(
    issue_category: PoliticianQuoteIssueCategory,
    politician_id: string,
    data: PoliticianQuoteModel
  ): Promise<PoliticianQuoteModel[]> {
    const index = createIndexIssueCategoryPoliticianId(
      issue_category,
      politician_id
    );

    const values = PoliticianQuoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete politician_quote by IssueCategoryPoliticianId index
   */
  async deletePoliticianQuoteByIssueCategoryPoliticianId(
    issue_category: PoliticianQuoteIssueCategory,
    politician_id: string
  ): Promise<void> {
    const index = createIndexIssueCategoryPoliticianId(
      issue_category,
      politician_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to PoliticianQuoteModel data array
   */
  private resultToData(values: Data[]): PoliticianQuoteModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return PoliticianQuoteModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as PoliticianQuoteModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized PoliticianQuoteModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is PoliticianQuoteModel => item !== null);
  }
}

/**
 * Convert PoliticianQuoteModel data to Value array
 */
function PoliticianQuoteModelToValues(data: PoliticianQuoteModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'politician_id', type: DataType.string, defaultValue: '' },
    { key: 'quote_text', type: DataType.string, defaultValue: '' },
    { key: 'issue_category', type: DataType.enumeration, defaultValue: 0 },
    { key: 'source', type: DataType.string, defaultValue: '' },
    { key: 'date_stated', type: DataType.string, defaultValue: '' },
    { key: 'context', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof PoliticianQuoteModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to PoliticianQuoteModel data
 */
function PoliticianQuoteModelFromValues(values: Value[]): PoliticianQuoteModel {
  const data: Partial<PoliticianQuoteModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'politician_id':
        data.politician_id = ParseValue(value, DataType.string) as string;
        break;
      case 'quote_text':
        data.quote_text = ParseValue(value, DataType.string) as string;
        break;
      case 'issue_category':
        data.issue_category = ParseValue(value, DataType.enumeration) as PoliticianQuoteIssueCategory;
        break;
      case 'source':
        data.source = ParseValue(value, DataType.string) as string;
        break;
      case 'date_stated':
        data.date_stated = ParseValue(value, DataType.string) as string;
        break;
      case 'context':
        data.context = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as PoliticianQuoteModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for PoliticianId fields
 */
function createIndexPoliticianId(
  politician_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, politician_id, 'politician_id'),
  ];

  return {
    fields: ['politician_id'],
    values
  };
}
/**
 * Create index for IssueCategoryPoliticianId fields
 */
function createIndexIssueCategoryPoliticianId(
  issue_category: PoliticianQuoteIssueCategory,
  politician_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, issue_category, 'issue_category'),
    CreateValue(DataType.string, politician_id, 'politician_id'),
  ];

  return {
    fields: ['issue_category', 'politician_id'],
    values
  };
}

export default PoliticianQuoteORM;