// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: bill.
// - Entity ID: 102019a23cf05777c37b214ec061f63ea0d.
// - Entity Version: 102019a27699e0f7060941f7dffce67a884.
// - Task ID: 68ffd975a776938453c6e20b.
// - Task Root ID: 68feec8dcd635a6ece0a6396.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for BillIssueCategory
 */
export enum BillIssueCategory {
  Unspecified = 0,
  Immigration = 1,
  Healthcare = 2,
  ClimateChange = 3,
  NationalDebt = 4,
  WarAuthorization = 5,
  GunControl = 6,
  Infrastructure = 7,
  Abortion = 8,
  SocialSecurity = 9,
  CivilRights = 10,
}



/**
 * Interface for BillModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface BillModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  bill_name: string;
  bill_number: string;
  year: number;
  description: string;
  issue_category: BillIssueCategory;
  final_yes_votes: number;
  final_no_votes: number;
  final_abstain_votes: number;
  impact_rank?: number | null;
  passed: boolean;
  date_voted: string;
}

/**
 * ORM class for Bill entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class BillORM {
  private static instance: BillORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a23cf05777c37b214ec061f63ea0d';
    this.entityName = 'bill';
    this.entityVersion = '102019a27699e0f7060941f7dffce67a884';
    this.taskId = '68ffd975a776938453c6e20b';
    this.taskRootId = '68feec8dcd635a6ece0a6396';
  }

  /**
   * Get singleton instance of BillORM
   */
  public static getInstance(): BillORM {
    if (!BillORM.instance) {
      BillORM.instance = new BillORM();
    }
    
    return BillORM.instance;
  }

  /**
   * Get all Bill records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllBill(): Promise<BillModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Bill record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertBill(data: BillModel[]): Promise<BillModel[]> {
    const structured = data.map((item) => CreateData(BillModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Bill records
   */
  async purgeAllBill(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Bill records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listBill(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[BillModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get bill by Id index
   * This function gets data by index.
   */
  async getBillById(
    id: string,
  ): Promise<BillModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bill by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBillById(
    id: string,
    data: BillModel
  ): Promise<BillModel[]> {
    const index = createIndexId(
      id
    );

    const values = BillModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bill by Id index
   */
  async deleteBillById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get bill by DataCreator index
   * This function gets data by index.
   */
  async getBillByDataCreator(
    data_creator: string,
  ): Promise<BillModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bill by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBillByDataCreator(
    data_creator: string,
    data: BillModel
  ): Promise<BillModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = BillModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bill by DataCreator index
   */
  async deleteBillByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get bill by DataUpdater index
   * This function gets data by index.
   */
  async getBillByDataUpdater(
    data_updater: string,
  ): Promise<BillModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bill by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBillByDataUpdater(
    data_updater: string,
    data: BillModel
  ): Promise<BillModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = BillModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bill by DataUpdater index
   */
  async deleteBillByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get bill by BillNumber index
   * This function gets data by index.
   */
  async getBillByBillNumber(
    bill_number: string,
  ): Promise<BillModel[]> {
    const index = createIndexBillNumber(
      bill_number
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bill by BillNumber index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBillByBillNumber(
    bill_number: string,
    data: BillModel
  ): Promise<BillModel[]> {
    const index = createIndexBillNumber(
      bill_number
    );

    const values = BillModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bill by BillNumber index
   */
  async deleteBillByBillNumber(
    bill_number: string
  ): Promise<void> {
    const index = createIndexBillNumber(
      bill_number
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get bill by IssueCategory index
   * This function gets data by index.
   */
  async getBillByIssueCategory(
    issue_category: BillIssueCategory,
  ): Promise<BillModel[]> {
    const index = createIndexIssueCategory(
      issue_category
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bill by IssueCategory index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBillByIssueCategory(
    issue_category: BillIssueCategory,
    data: BillModel
  ): Promise<BillModel[]> {
    const index = createIndexIssueCategory(
      issue_category
    );

    const values = BillModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bill by IssueCategory index
   */
  async deleteBillByIssueCategory(
    issue_category: BillIssueCategory
  ): Promise<void> {
    const index = createIndexIssueCategory(
      issue_category
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get bill by ImpactRank index
   * This function gets data by index.
   */
  async getBillByImpactRank(
    impact_rank: number,
  ): Promise<BillModel[]> {
    const index = createIndexImpactRank(
      impact_rank
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bill by ImpactRank index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBillByImpactRank(
    impact_rank: number,
    data: BillModel
  ): Promise<BillModel[]> {
    const index = createIndexImpactRank(
      impact_rank
    );

    const values = BillModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bill by ImpactRank index
   */
  async deleteBillByImpactRank(
    impact_rank: number
  ): Promise<void> {
    const index = createIndexImpactRank(
      impact_rank
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get bill by Year index
   * This function gets data by index.
   */
  async getBillByYear(
    year: number,
  ): Promise<BillModel[]> {
    const index = createIndexYear(
      year
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bill by Year index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBillByYear(
    year: number,
    data: BillModel
  ): Promise<BillModel[]> {
    const index = createIndexYear(
      year
    );

    const values = BillModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bill by Year index
   */
  async deleteBillByYear(
    year: number
  ): Promise<void> {
    const index = createIndexYear(
      year
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to BillModel data array
   */
  private resultToData(values: Data[]): BillModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return BillModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as BillModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized BillModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is BillModel => item !== null);
  }
}

/**
 * Convert BillModel data to Value array
 */
function BillModelToValues(data: BillModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'bill_name', type: DataType.string, defaultValue: '' },
    { key: 'bill_number', type: DataType.string, defaultValue: '' },
    { key: 'year', type: DataType.number, defaultValue: 0 },
    { key: 'description', type: DataType.string, defaultValue: '' },
    { key: 'issue_category', type: DataType.enumeration, defaultValue: 0 },
    { key: 'final_yes_votes', type: DataType.number, defaultValue: 0 },
    { key: 'final_no_votes', type: DataType.number, defaultValue: 0 },
    { key: 'final_abstain_votes', type: DataType.number, defaultValue: 0 },
    { key: 'impact_rank', type: DataType.number, defaultValue: null },
    { key: 'passed', type: DataType.boolean, defaultValue: false },
    { key: 'date_voted', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof BillModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to BillModel data
 */
function BillModelFromValues(values: Value[]): BillModel {
  const data: Partial<BillModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'bill_name':
        data.bill_name = ParseValue(value, DataType.string) as string;
        break;
      case 'bill_number':
        data.bill_number = ParseValue(value, DataType.string) as string;
        break;
      case 'year':
        data.year = ParseValue(value, DataType.number) as number;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string;
        break;
      case 'issue_category':
        data.issue_category = ParseValue(value, DataType.enumeration) as BillIssueCategory;
        break;
      case 'final_yes_votes':
        data.final_yes_votes = ParseValue(value, DataType.number) as number;
        break;
      case 'final_no_votes':
        data.final_no_votes = ParseValue(value, DataType.number) as number;
        break;
      case 'final_abstain_votes':
        data.final_abstain_votes = ParseValue(value, DataType.number) as number;
        break;
      case 'impact_rank':
        data.impact_rank = ParseValue(value, DataType.number) as number | null;
        break;
      case 'passed':
        data.passed = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'date_voted':
        data.date_voted = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as BillModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for BillNumber fields
 */
function createIndexBillNumber(
  bill_number: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, bill_number, 'bill_number'),
  ];

  return {
    fields: ['bill_number'],
    values
  };
}
/**
 * Create index for IssueCategory fields
 */
function createIndexIssueCategory(
  issue_category: BillIssueCategory
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, issue_category, 'issue_category'),
  ];

  return {
    fields: ['issue_category'],
    values
  };
}
/**
 * Create index for ImpactRank fields
 */
function createIndexImpactRank(
  impact_rank: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, impact_rank, 'impact_rank'),
  ];

  return {
    fields: ['impact_rank'],
    values
  };
}
/**
 * Create index for Year fields
 */
function createIndexYear(
  year: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, year, 'year'),
  ];

  return {
    fields: ['year'],
    values
  };
}

export default BillORM;