// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: voting_record.
// - Entity ID: 102019a23cf05777f3283045656e2779179.
// - Entity Version: 102019a27699e0f7060941f7dffce67a884.
// - Task ID: 68ffd975a776938453c6e20b.
// - Task Root ID: 68feec8dcd635a6ece0a6396.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for VotingRecordVoteChoice
 */
export enum VotingRecordVoteChoice {
  Unspecified = 0,
  Yes = 1,
  No = 2,
  Abstain = 3,
}



/**
 * Interface for VotingRecordModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface VotingRecordModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  politician_id: string;
  bill_id: string;
  vote_choice: VotingRecordVoteChoice;
  date_recorded: string;
  notes?: string | null;
}

/**
 * ORM class for VotingRecord entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class VotingRecordORM {
  private static instance: VotingRecordORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a23cf05777f3283045656e2779179';
    this.entityName = 'voting_record';
    this.entityVersion = '102019a27699e0f7060941f7dffce67a884';
    this.taskId = '68ffd975a776938453c6e20b';
    this.taskRootId = '68feec8dcd635a6ece0a6396';
  }

  /**
   * Get singleton instance of VotingRecordORM
   */
  public static getInstance(): VotingRecordORM {
    if (!VotingRecordORM.instance) {
      VotingRecordORM.instance = new VotingRecordORM();
    }
    
    return VotingRecordORM.instance;
  }

  /**
   * Get all VotingRecord records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllVotingRecord(): Promise<VotingRecordModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new VotingRecord record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertVotingRecord(data: VotingRecordModel[]): Promise<VotingRecordModel[]> {
    const structured = data.map((item) => CreateData(VotingRecordModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all VotingRecord records
   */
  async purgeAllVotingRecord(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List VotingRecord records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listVotingRecord(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[VotingRecordModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get voting_record by Id index
   * This function gets data by index.
   */
  async getVotingRecordById(
    id: string,
  ): Promise<VotingRecordModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voting_record by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVotingRecordById(
    id: string,
    data: VotingRecordModel
  ): Promise<VotingRecordModel[]> {
    const index = createIndexId(
      id
    );

    const values = VotingRecordModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voting_record by Id index
   */
  async deleteVotingRecordById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get voting_record by DataCreator index
   * This function gets data by index.
   */
  async getVotingRecordByDataCreator(
    data_creator: string,
  ): Promise<VotingRecordModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voting_record by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVotingRecordByDataCreator(
    data_creator: string,
    data: VotingRecordModel
  ): Promise<VotingRecordModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = VotingRecordModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voting_record by DataCreator index
   */
  async deleteVotingRecordByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get voting_record by DataUpdater index
   * This function gets data by index.
   */
  async getVotingRecordByDataUpdater(
    data_updater: string,
  ): Promise<VotingRecordModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voting_record by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVotingRecordByDataUpdater(
    data_updater: string,
    data: VotingRecordModel
  ): Promise<VotingRecordModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = VotingRecordModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voting_record by DataUpdater index
   */
  async deleteVotingRecordByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get voting_record by PoliticianId index
   * This function gets data by index.
   */
  async getVotingRecordByPoliticianId(
    politician_id: string,
  ): Promise<VotingRecordModel[]> {
    const index = createIndexPoliticianId(
      politician_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voting_record by PoliticianId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVotingRecordByPoliticianId(
    politician_id: string,
    data: VotingRecordModel
  ): Promise<VotingRecordModel[]> {
    const index = createIndexPoliticianId(
      politician_id
    );

    const values = VotingRecordModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voting_record by PoliticianId index
   */
  async deleteVotingRecordByPoliticianId(
    politician_id: string
  ): Promise<void> {
    const index = createIndexPoliticianId(
      politician_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get voting_record by BillId index
   * This function gets data by index.
   */
  async getVotingRecordByBillId(
    bill_id: string,
  ): Promise<VotingRecordModel[]> {
    const index = createIndexBillId(
      bill_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voting_record by BillId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVotingRecordByBillId(
    bill_id: string,
    data: VotingRecordModel
  ): Promise<VotingRecordModel[]> {
    const index = createIndexBillId(
      bill_id
    );

    const values = VotingRecordModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voting_record by BillId index
   */
  async deleteVotingRecordByBillId(
    bill_id: string
  ): Promise<void> {
    const index = createIndexBillId(
      bill_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get voting_record by BillIdPoliticianId index
   * This function gets data by index.
   */
  async getVotingRecordByBillIdPoliticianId(
    bill_id: string,
    politician_id: string,
  ): Promise<VotingRecordModel[]> {
    const index = createIndexBillIdPoliticianId(
      bill_id,
      politician_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) voting_record by BillIdPoliticianId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVotingRecordByBillIdPoliticianId(
    bill_id: string,
    politician_id: string,
    data: VotingRecordModel
  ): Promise<VotingRecordModel[]> {
    const index = createIndexBillIdPoliticianId(
      bill_id,
      politician_id
    );

    const values = VotingRecordModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete voting_record by BillIdPoliticianId index
   */
  async deleteVotingRecordByBillIdPoliticianId(
    bill_id: string,
    politician_id: string
  ): Promise<void> {
    const index = createIndexBillIdPoliticianId(
      bill_id,
      politician_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to VotingRecordModel data array
   */
  private resultToData(values: Data[]): VotingRecordModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return VotingRecordModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as VotingRecordModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized VotingRecordModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is VotingRecordModel => item !== null);
  }
}

/**
 * Convert VotingRecordModel data to Value array
 */
function VotingRecordModelToValues(data: VotingRecordModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'politician_id', type: DataType.string, defaultValue: '' },
    { key: 'bill_id', type: DataType.string, defaultValue: '' },
    { key: 'vote_choice', type: DataType.enumeration, defaultValue: 0 },
    { key: 'date_recorded', type: DataType.string, defaultValue: '' },
    { key: 'notes', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof VotingRecordModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to VotingRecordModel data
 */
function VotingRecordModelFromValues(values: Value[]): VotingRecordModel {
  const data: Partial<VotingRecordModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'politician_id':
        data.politician_id = ParseValue(value, DataType.string) as string;
        break;
      case 'bill_id':
        data.bill_id = ParseValue(value, DataType.string) as string;
        break;
      case 'vote_choice':
        data.vote_choice = ParseValue(value, DataType.enumeration) as VotingRecordVoteChoice;
        break;
      case 'date_recorded':
        data.date_recorded = ParseValue(value, DataType.string) as string;
        break;
      case 'notes':
        data.notes = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as VotingRecordModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for PoliticianId fields
 */
function createIndexPoliticianId(
  politician_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, politician_id, 'politician_id'),
  ];

  return {
    fields: ['politician_id'],
    values
  };
}
/**
 * Create index for BillId fields
 */
function createIndexBillId(
  bill_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, bill_id, 'bill_id'),
  ];

  return {
    fields: ['bill_id'],
    values
  };
}
/**
 * Create index for BillIdPoliticianId fields
 */
function createIndexBillIdPoliticianId(
  bill_id: string,
  politician_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, bill_id, 'bill_id'),
    CreateValue(DataType.string, politician_id, 'politician_id'),
  ];

  return {
    fields: ['bill_id', 'politician_id'],
    values
  };
}

export default VotingRecordORM;